### 本地测试 单日
GET http://localhost:8000/api/daily?date=20250521
### 本地测试 多日
GET http://localhost:8000/api/date-range/count-area?start=20250501&end=20250523
### 本地测试 项目 1
GET http://localhost:8000/api/project?licenseNo=(平)第2015-001号
### 本地测试 项目 2
GET http://localhost:8000/api/project?projectName=万丰大厦
### 本地测试 项目 3
GET http://localhost:8000/api/project?projectName=万
### 本地测试 项目 周期 1
GET http://localhost:8000/api/date-range/project?start=20250501&end=20250523&licenseNo=温房预许字（2024）第00215号

### Render测试
GET https://shujuwenfang.onrender.com/api/daily?date=20250501

### Render测试 项目 周期 1
GET https://shujuwenfang.onrender.com/api/date-range/project?start=20250501&end=20250523&licenseNo=温房预许字（2024）第00215号
### Render测试 项目 周期 2
GET https://shujuwenfang.onrender.com/api/date-range/project?start=20250424&end=20250524&licenseNo=%E6%B8%A9%E6%88%BF%E5%94%AE%E8%AE%B8%E5%AD%97(2021)%E7%AC%AC106%E5%8F%B7
