CREATE TABLE projects (
    project_id NUMERIC(14, 0) PRIMARY KEY,
    company_id NUMERIC(14, 0),
    company_name VARCHAR(50),
    license_no VARCHAR(50),
    license_date DATE,
    region SMALLINT,
    district VARCHAR(50),
    project_name VARCHAR(100),
    project_address VARCHAR(120),
    sales_date TIMESTAMP,
    sales_address VARCHAR(100),
    sales_contact_no VARCHAR(50),
    total_units INTEGER,
    available_units INTEGER,
    residential_units INTEGER,
    reserved_units INTEGER DEFAULT 0,
    booked_units INTEGER DEFAULT 0,
    sold_units INTEGER DEFAULT 0,
    registered_units INTEGER DEFAULT 0,
    relocation_housing_units INTEGER DEFAULT 0,
    restricted_units INTEGER DEFAULT 0,
    non_sale_units INTEGER DEFAULT 0,
    total_area_sqm NUMERIC(10, 2),
    available_area_sqm NUMERIC(10, 2),
    residential_area_sqm NUMERIC(10, 2),
    reserved_area_sqm NUMERIC(10, 2) DEFAULT 0,
    booked_area_sqm NUMERIC(10, 2) DEFAULT 0,
    sold_area_sqm NUMERIC(10, 2) DEFAULT 0,
    registered_area_sqm NUMERIC(10, 2) DEFAULT 0,
    relocation_housing_area_sqm NUMERIC(10, 2) DEFAULT 0,
    restricted_area_sqm NUMERIC(10, 2) DEFAULT 0,
    non_sale_area_sqm NUMERIC(10, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_projects_project_name_trgm ON projects USING gin (project_name gin_trgm_ops);
select * from projects where project_name ilike '%天%'